/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bWc6JQObpk0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function Dashboard() {
  return (
    (<div className="w-full max-w-5xl mx-auto px-4 md:px-6 py-12">
      <div className="grid md:grid-cols-2 gap-8">
        <div>
          <h1 className="text-3xl font-bold mb-4">Lost Items</h1>
          <div className="border rounded-lg overflow-hidden">
            <div className="bg-muted p-4 flex items-center justify-between">
              <h2 className="text-lg font-semibold">Report a Lost Item</h2>
              <Button>Report</Button>
            </div>
            <div className="p-4 grid gap-4">
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="ref-number">Reference #</Label>
                <Input id="ref-number" placeholder="LI-001" />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="tags">Tags</Label>
                <Select id="tags" multiple>
                  <SelectTrigger>
                    <SelectValue placeholder="Select tags" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="clothing">Clothing</SelectItem>
                    <SelectItem value="electronics">Electronics</SelectItem>
                    <SelectItem value="keys">Keys</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="location">Location</Label>
                <Input id="location" placeholder="Campus Library" />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="images">Images</Label>
                <Input id="images" type="file" multiple />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="location-found">Description</Label>
                <textarea id="location-found" placeholder="Campus Library" />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="date-time">Date & Time</Label>
                <div className="flex items-center gap-2">
                  <Input id="date-time" type="datetime-local" />
                  <Button variant="ghost" size="icon">
                    <CalendarIcon className="h-5 w-5" />
                  </Button>
                </div>
              </div>
              <Button type="submit" className="justify-self-end">
                Submit
              </Button>
            </div>
          </div>
        </div>
        <div>
          <h1 className="text-3xl font-bold mb-4">Found Items</h1>
          <div className="border rounded-lg overflow-hidden">
            <div className="bg-muted p-4 flex items-center justify-between">
              <h2 className="text-lg font-semibold">Report a Found Item</h2>
              <Button>Report</Button>
            </div>
            <div className="p-4 grid gap-4">
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="ref-number-found">Reference #</Label>
                <Input id="ref-number-found" placeholder="FI-001" />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="tags-found">Tags</Label>
                <Select id="tags-found" multiple>
                  <SelectTrigger>
                    <SelectValue placeholder="Select tags" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="clothing">Clothing</SelectItem>
                    <SelectItem value="electronics">Electronics</SelectItem>
                    <SelectItem value="keys">Keys</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="location-found">Location</Label>
                <Input id="location-found" placeholder="Campus Library" />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="images-found">Images</Label>
                <Input id="images-found" type="file" multiple />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="location-found">Description</Label>
                <textarea id="location-found" placeholder="Campus Library" />
              </div>
              <div className="grid grid-cols-[100px_1fr] gap-4">
                <Label htmlFor="date-time-found">Date & Time</Label>
                <div className="flex items-center gap-2">
                  <Input id="date-time-found" type="datetime-local" />
                  <Button variant="ghost" size="icon">
                    <CalendarIcon className="h-5 w-5" />
                  </Button>
                </div>
              </div>
              <Button type="submit" className="justify-self-end">
                Submit
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div className="mt-12">
        <Tabs defaultValue="lost">
          <TabsList>
            <TabsTrigger value="lost">Lost Items</TabsTrigger>
            <TabsTrigger value="found">Found Items</TabsTrigger>
          </TabsList>
          <TabsContent value="lost">
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Black Leather Wallet</CardTitle>
                  <CardDescription>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline">Clothing</Badge>
                      <Badge variant="outline">Keys</Badge>
                    </div>
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-[100px_1fr] gap-4">
                    <div>
                      <img
                        src="/placeholder.svg"
                        alt="Lost Item"
                        width={100}
                        height={100}
                        className="rounded-md object-cover"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }} />
                    </div>
                    <div>
                      <p>
                        <span className="font-medium">Reference #:</span> LI-001
                      </p>
                      <p>
                        <span className="font-medium">Location:</span> Campus Library
                      </p>
                      <p>
                        <span className="font-medium">Date & Time:</span> May 15, 2023 - 2:30 PM
                      </p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button variant="outline">Contact Owner</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>iPhone 13 Pro</CardTitle>
                  <CardDescription>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline">Electronics</Badge>
                    </div>
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-[100px_1fr] gap-4">
                    <div>
                      <img
                        src="/placeholder.svg"
                        alt="Lost Item"
                        width={100}
                        height={100}
                        className="rounded-md object-cover"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }} />
                    </div>
                    <div>
                      <p>
                        <span className="font-medium">Reference #:</span> LI-002
                      </p>
                      <p>
                        <span className="font-medium">Location:</span> Student Center
                      </p>
                      <p>
                        <span className="font-medium">Date & Time:</span> May 20, 2023 - 4:45 PM
                      </p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button variant="outline">Contact Owner</Button>
                </CardFooter>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="found">
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Car Keys</CardTitle>
                  <CardDescription>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline">Keys</Badge>
                    </div>
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-[100px_1fr] gap-4">
                    <div>
                      <img
                        src="/placeholder.svg"
                        alt="Found Item"
                        width={100}
                        height={100}
                        className="rounded-md object-cover"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }} />
                    </div>
                    <div>
                      <p>
                        <span className="font-medium">Reference #:</span> FI-001
                      </p>
                      <p>
                        <span className="font-medium">Location:</span> Cafeteria
                      </p>
                      <p>
                        <span className="font-medium">Date & Time:</span> May 18, 2023 - 12:15 PM
                      </p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button variant="outline">Claim Item</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Backpack</CardTitle>
                  <CardDescription>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline">Clothing</Badge>
                    </div>
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-[100px_1fr] gap-4">
                    <div>
                      <img
                        src="/placeholder.svg"
                        alt="Found Item"
                        width={100}
                        height={100}
                        className="rounded-md object-cover"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }} />
                    </div>
                    <div>
                      <p>
                        <span className="font-medium">Reference #:</span> FI-002
                      </p>
                      <p>
                        <span className="font-medium">Location:</span> Main Entrance
                      </p>
                      <p>
                        <span className="font-medium">Date & Time:</span> May 22, 2023 - 9:30 AM
                      </p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button variant="outline">Claim Item</Button>
                </CardFooter>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>)
  );
}

function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}
